-- Onsager #511 (#506 Phase 2, governed by ADR 0024) — pin the
-- workflow-library version each run compiled against.
--
-- A plan recovered after a host restart silently recompiled against the
-- *latest* workflow-library version, not the version it was registered
-- with: `recover_running_plans` rebuilds each plan via the library's
-- `lookup(kind)`, which returns `latest()`. If a new workflow version
-- was registered between a plan starting and the host restarting, the
-- in-flight plan resumed on a different compiled graph — and failed at
-- runtime if node/gate signatures changed.
--
-- `kind_versions` maps each referenced spec `kind` to the
-- `workflow_library.version` resolved at registration. Recovery looks
-- each kind up at its pinned version; an absent map (legacy rows) or a
-- retired pinned version (`retired_at IS NOT NULL`) falls back to
-- `latest()` with a logged warning so the divergence is observable.
--
-- Additive with a safe default so existing `running` rows recover with
-- today's latest-lookup behavior (empty map ⇒ no pins ⇒ `latest()`).
-- The scheduler host ensures this column idempotently at startup
-- (crates/onsager-scheduler/src/migrate.rs) alongside migration 006.
ALTER TABLE execution_plans
    ADD COLUMN IF NOT EXISTS kind_versions JSONB NOT NULL DEFAULT '{}';
