-- Relax workflows.trigger_kind CHECK constraint (spec #237).
--
-- The CHECK (trigger_kind IN ('github_issue_webhook')) added in
-- migration 006 made every new TriggerKind variant a schema change —
-- defeating the registry-driven extension point spec #237 establishes.
--
-- The registry manifest in `crates/onsager-registry/src/triggers.rs`
-- now owns the canonical list. `workflow_db::insert_workflow_with_stages`
-- validates inserts against `TRIGGERS.lookup(...)` before they reach
-- the DB, so unknown kinds still fail with a clear error — without
-- requiring a migration in every environment for each new kind.
--
-- The CHECK constraint name is auto-generated by Postgres as
-- `workflows_trigger_kind_check`. ALTER TABLE ... DROP CONSTRAINT IF
-- EXISTS is idempotent so re-running the migration on a DB that's
-- already had it dropped (or one created without it) is a no-op.

ALTER TABLE workflows
    DROP CONSTRAINT IF EXISTS workflows_trigger_kind_check;
