// budget-allow: factory event enum (~50+ variants after spec #272 prune + #274 cut); macro/derive compression deferred to follow-up spec per #261
//! Factory events — the authoritative event types emitted to the factory event
//! spine by each subsystem.
//!
//! See `specs/forge-v0.1.md §9` for the Forge event contract. Additional event
//! types from Stiglab, Synodic, and Ising are included here so that the spine
//! library provides a single typed vocabulary.

use chrono::{DateTime, Utc};
use onsager_artifact::{ArtifactId, ArtifactState, Kind};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Factory event envelope
// ---------------------------------------------------------------------------

/// A factory event as written to the event spine.
///
/// All subsystems write events through this envelope. The `event` field carries
/// the typed payload; the wrapper carries tracing metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FactoryEvent {
    /// The typed event payload.
    pub event: FactoryEventKind,
    /// Correlation ID for tracing a causal chain of events.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// ID of the event that caused this one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<i64>,
    /// The subsystem or actor that produced this event.
    pub actor: String,
    /// Timestamp (usually DB-assigned, but included for serialization).
    pub timestamp: DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// Typed event payloads
// ---------------------------------------------------------------------------

/// All factory event types across all subsystems.
///
/// ## Forge events (authoritative per forge-v0.1 §9)
///
/// ## Stiglab events (session lifecycle upgrades)
///
/// ## Synodic events (rule and escalation outcomes)
///
/// ## Ising events (insight records)
///
/// `f64` fields (confidence) block `Eq`; only `PartialEq` is derived.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum FactoryEventKind {
    // -- Artifact lifecycle (Forge) -----------------------------------------
    /// New artifact accepted and ID assigned.
    ArtifactRegistered {
        artifact_id: ArtifactId,
        kind: Kind,
        name: String,
        owner: String,
    },

    /// Artifact transitioned between lifecycle states.
    ArtifactStateChanged {
        artifact_id: ArtifactId,
        from_state: ArtifactState,
        to_state: ArtifactState,
    },

    /// Artifact reached terminal state (archived).
    ArtifactArchived {
        artifact_id: ArtifactId,
        reason: String,
    },

    // -- Git lifecycle events -------------------------------------------------
    GitPrOpened {
        artifact_id: ArtifactId,
        repo: String,
        pr_number: u64,
        url: String,
    },
    GitCiCompleted {
        artifact_id: ArtifactId,
        pr_number: u64,
        check_name: String,
        conclusion: String,
    },
    GitPrMerged {
        artifact_id: ArtifactId,
        pr_number: u64,
        merge_sha: String,
    },
    GitPrClosed {
        artifact_id: ArtifactId,
        pr_number: u64,
    },

    // -- Forge process events -----------------------------------------------
    /// ShapingRequest sent to Stiglab.
    ForgeShapingDispatched {
        request_id: String,
        artifact_id: ArtifactId,
        target_version: u32,
        /// Full shaping payload — the same shape Stiglab previously
        /// consumed as the `POST /api/shaping` request body. `None` on
        /// events written before this field was added (spec #131 / ADR
        /// 0004 Lever C phase 3). When `None`, Stiglab's listener cannot
        /// spawn a session and must skip the request.
        ///
        /// Top-level `request_id`, `artifact_id`, and `target_version`
        /// are kept for stream indexing and dashboard filtering; the
        /// duplication with `request` is intentional.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request: Option<crate::protocol::ShapingRequest>,
    },

    /// ShapingResult received from Stiglab.
    ForgeShapingReturned {
        request_id: String,
        artifact_id: ArtifactId,
        outcome: ShapingOutcome,
    },

    /// GateRequest sent to Synodic.
    ForgeGateRequested {
        /// Correlation ID generated by Forge when emitting the request.
        /// Synodic echoes it back on `synodic.gate_verdict` so Forge can
        /// match the verdict to its parked pipeline decision.
        ///
        /// `#[serde(default)]` allows older events written before spec
        /// #131 / ADR 0004 Lever C to deserialize with an empty id.
        #[serde(default)]
        gate_id: String,
        artifact_id: ArtifactId,
        gate_point: GatePoint,
        /// Full gate-evaluation payload — the same shape Synodic
        /// previously consumed as the `POST /api/gate` request body.
        /// `None` on events written before this field was added (spec
        /// #131 / ADR 0004 Lever C phase 2). When `None`, Synodic's
        /// listener cannot evaluate and must skip the request.
        ///
        /// Top-level `gate_id`, `artifact_id`, and `gate_point` are
        /// kept for stream indexing and dashboard filtering; the
        /// duplication with `request.context` is intentional.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request: Option<crate::protocol::GateRequest>,
    },

    /// GateVerdict received from Synodic.
    ForgeGateVerdict {
        artifact_id: ArtifactId,
        gate_point: GatePoint,
        verdict: VerdictSummary,
    },

    /// Insight forwarded to the scheduling kernel.
    ForgeInsightObserved {
        insight_id: String,
        insight_kind: InsightKind,
        scope: InsightScope,
    },

    /// Scheduling kernel produced a ShapingDecision.
    ForgeDecisionMade {
        artifact_id: ArtifactId,
        target_version: u32,
        priority: i32,
    },

    // -- Stiglab events (session lifecycle) ---------------------------------
    /// A session finished successfully.
    StiglabSessionCompleted {
        session_id: String,
        request_id: String,
        duration_ms: u64,
        /// Artifact this session was shaping (issue #14 phase 2). Optional so
        /// non-shaping sessions (e.g. direct task POSTs) don't emit a
        /// meaningless id.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        artifact_id: Option<String>,
        /// LLM token usage for this session (issue #39). Optional so
        /// pre-accounting sessions and mock dispatchers don't fabricate a
        /// zero bill — `None` means "not reported", not "cost nothing".
        #[serde(default, skip_serializing_if = "Option::is_none")]
        token_usage: Option<TokenUsage>,
        /// Working-tree branch the agent pushed at session completion (issue
        /// #60). Used by `onsager-portal` to attach `vertical_lineage` when
        /// the matching PR webhook arrives. Optional — sessions that don't
        /// touch a git working dir leave it `None`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        branch: Option<String>,
        /// PR number the agent opened, when known at completion time.
        /// Optional for the same reasons as `branch`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pr_number: Option<u64>,
    },

    /// Full `ShapingResult` produced by a Stiglab session, ready for
    /// Forge to act on. Replaces the legacy synchronous
    /// `forge → stiglab POST /api/shaping` HTTP response per spec #131
    /// / ADR 0004 Lever C.
    ///
    /// Emitted in addition to (not instead of) `stiglab.session_completed`:
    /// the lifecycle event signals "this session finished" (used by the
    /// dashboard and node telemetry); this event signals "the artifact
    /// outputs are ready for the next pipeline stage" (used by Forge's
    /// state machine to advance / seal). Stiglab emits it only for
    /// sessions that were dispatched as shaping requests — direct task
    /// POSTs that produce no `ShapingResult` skip it.
    StiglabShapingResultReady {
        /// Artifact this shaping was for. Hoisted so `stream_id()` can
        /// route the event without parsing the embedded result.
        artifact_id: ArtifactId,
        /// Full result payload — the same shape Forge previously
        /// consumed as the `POST /api/shaping` response body.
        /// `request_id` inside this struct correlates back to the
        /// originating `forge.shaping_dispatched`.
        result: crate::protocol::ShapingResult,
    },

    /// A session terminated with an error.
    StiglabSessionFailed {
        session_id: String,
        request_id: String,
        error: String,
        /// Artifact this session was shaping (issue #156). Optional so
        /// non-shaping sessions (direct task POSTs) don't emit a
        /// meaningless id. When present, forge's workflow signal
        /// listener writes a `Failure` outcome to the agent-session
        /// signal cache so the gate fails loudly instead of stalling.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        artifact_id: Option<String>,
    },

    /// A session was aborted (e.g. node lost, deadline exceeded).
    StiglabSessionAborted { session_id: String, reason: String },

    // -- Portal intents (dashboard → agent dispatch) -------------------------
    /// Dashboard task request from portal. Stiglab's
    /// `session_requested_listener` dispatches the session to the correct
    /// agent node (spec #222 Follow-up 3).
    PortalSessionRequested { session_id: String },

    // -- Synodic events (governance) ----------------------------------------
    /// A gate request was evaluated and a verdict issued.
    SynodicGateEvaluated {
        gate_id: String,
        artifact_id: ArtifactId,
        verdict: VerdictSummary,
    },

    /// A gate request was denied (subset of gate_evaluated, for easy filtering).
    SynodicGateDenied {
        gate_id: String,
        artifact_id: ArtifactId,
        reason: String,
    },

    /// A gate request verdict was Modify (subset of gate_evaluated).
    SynodicGateModified {
        gate_id: String,
        artifact_id: ArtifactId,
    },

    /// Full gate verdict issued by Synodic in response to a
    /// `forge.gate_requested` event. Carries the complete `GateVerdict`
    /// payload — Allow, Deny{reason}, Modify{new_action}, or
    /// Escalate{context} — so Forge can act on it without a follow-up
    /// HTTP roundtrip.
    ///
    /// Replaces the legacy synchronous `forge → synodic POST /api/gate`
    /// response per spec #131 / ADR 0004 Lever C. The summary variants
    /// above (`SynodicGateEvaluated`, `SynodicGateDenied`,
    /// `SynodicGateModified`) remain for dashboard filtering; this
    /// variant is the one consumers act on.
    SynodicGateVerdict {
        /// Correlation ID echoed from the originating
        /// `forge.gate_requested` event.
        gate_id: String,
        artifact_id: ArtifactId,
        gate_point: GatePoint,
        verdict: crate::protocol::GateVerdict,
    },

    /// An escalation was initiated.
    SynodicEscalationStarted {
        escalation_id: String,
        artifact_id: ArtifactId,
    },

    /// An escalation was resolved (by human, delegate, or timeout).
    SynodicEscalationResolved {
        escalation_id: String,
        artifact_id: ArtifactId,
        resolution: EscalationResolution,
    },

    /// An escalation timed out and the default verdict was applied.
    SynodicEscalationTimedOut {
        escalation_id: String,
        artifact_id: ArtifactId,
    },

    /// A delegate (human or supervisor agent) proposed a resolution for an
    /// active escalation (issue #37). The resolution is not applied until
    /// accepted — this event is the proposal itself, not the final verdict.
    SynodicGateResolutionProposed {
        escalation_id: String,
        artifact_id: ArtifactId,
        /// Who's proposing the resolution (`"supervisor"`, `"human:<id>"`).
        proposer: String,
        /// The verdict being proposed.
        proposed_verdict: VerdictSummary,
        /// Free-form justification for the audit trail.
        rationale: String,
    },

    /// A crystallization candidate rule was created.
    SynodicRuleProposed {
        rule_id: String,
        description: String,
    },

    /// A proposed rule was approved and entered the active set.
    SynodicRuleApproved { rule_id: String },

    /// A rule was disabled.
    SynodicRuleDisabled { rule_id: String, reason: String },

    /// A rule was modified, producing a new version.
    SynodicRuleVersionCreated { rule_id: String, version: u32 },

    // -- Ising events (observation) -----------------------------------------
    /// An insight passed validation and was recorded on the spine.
    IsingInsightDetected {
        insight_id: String,
        kind: InsightKind,
        scope: InsightScope,
        observation: String,
        confidence: f64,
    },

    /// A structured signal Ising surfaces on the spine for other subsystems
    /// to consume (issue #36 — close the feedback loop). Unlike
    /// `IsingInsightDetected`, which carries a human-readable observation,
    /// this variant is the machine-readable edge: each emission names the
    /// signal kind, the subject it attaches to, and the events that evidence
    /// it. Forge tails these into `WorldState.insights`; a future Synodic
    /// consumer will treat high-confidence emissions as rule-proposal input.
    IsingInsightEmitted {
        /// Stable signal identifier (e.g. `"repeated_gate_override"`,
        /// `"shape_retry_spike"`). Consumers match on this string.
        signal_kind: String,
        /// What the signal is about — an artifact kind, artifact id, rule id,
        /// or intent class — serialized as a free-form string so the event
        /// contract doesn't need to know every possible subject type.
        subject_ref: String,
        /// Spine events that evidence this signal. Invariant: non-empty
        /// (enforced by the producer).
        evidence: Vec<EventRef>,
        /// 0.0..=1.0; downstream consumers use this to route (advisory vs.
        /// crystallization threshold).
        confidence: f64,
    },

    /// An insight was deduplicated or fell below confidence threshold (audit trail).
    IsingInsightSuppressed { insight_id: String, reason: String },

    /// An insight was packaged as a rule proposal for Synodic (issue #36
    /// Step 2). Unlike the legacy form, this variant carries enough
    /// structure that a Synodic consumer can route it without looking up
    /// the original insight — `signal_kind` + `subject_ref` identify the
    /// evidence, `proposed_action` names what rule change is being asked
    /// for, and `class` decides whether the proposal auto-activates
    /// (`safe_auto`) or enters the review queue (`review_required`).
    IsingRuleProposed {
        /// ID of the insight that motivated the proposal.
        insight_id: String,
        /// Copy of the producing analyzer's signal kind (e.g.
        /// `"repeated_gate_override"`) so consumers can dedupe against the
        /// `insight_emitted` stream.
        signal_kind: String,
        /// What the proposal is about (artifact kind, rule id, etc.).
        subject_ref: String,
        /// Kind of change being proposed.
        proposed_action: RuleProposalAction,
        /// How the proposal should be handled downstream.
        class: RuleProposalClass,
        /// Human-readable justification for the audit trail.
        rationale: String,
        /// Confidence copied from the backing insight (0.0..=1.0).
        confidence: f64,
    },

    /// An analyzer encountered an error during its run.
    IsingAnalyzerError { analyzer: String, error: String },

    /// Ising finished catching up from a lag position.
    IsingCatchupCompleted { events_processed: u64 },

    // -- Refract events (issue #35 — intent decomposition) ------------------
    /// A new intent was submitted for decomposition. Intents are the
    /// high-level units of work a Refract decomposer expands into artifact
    /// trees (e.g. `"migrate all legacy auth callers to the new SDK"` →
    /// one artifact per file-touchpoint).
    IntentSubmitted {
        /// Opaque unique id — used as the correlation handle for every
        /// downstream `refract.*` event.
        intent_id: String,
        /// Stable class identifier — maps 1:1 to a registered decomposer
        /// (e.g. `"file_migration"`, `"spec_rollout"`).
        intent_class: String,
        /// Free-form description of the intent, shown in the UI and
        /// preserved as audit trail.
        description: String,
        /// Who or what submitted the intent.
        submitter: String,
    },

    /// A decomposer produced an artifact tree for an intent.
    RefractDecomposed {
        intent_id: String,
        /// Name of the decomposer that handled the intent (the Refract
        /// equivalent of Ising's `signal_kind`).
        decomposer: String,
        /// Newly registered artifact ids produced by the decomposition.
        artifact_ids: Vec<String>,
    },

    /// Decomposition failed — either no decomposer matched, or the matched
    /// decomposer errored out.
    RefractFailed { intent_id: String, reason: String },

    // -- Workflow runtime events (issue #80) --------------------------------
    /// A trigger (e.g. a GitHub issue webhook) fired and produced a payload
    /// the trigger subscriber will translate into an artifact registration.
    /// Emitted by the stiglab webhook receiver; consumed by forge.
    TriggerFired {
        /// Workflow whose trigger fired.
        workflow_id: String,
        /// Trigger classification (matches the `workflows.trigger_kind`
        /// column). v1 always `"github_issue_webhook"`.
        trigger_kind: String,
        /// Free-form payload the subscriber needs to translate the trigger
        /// into an artifact (e.g. issue number, title, body, repo).
        payload: serde_json::Value,
    },

    /// Audit record for a manual / CLI / replay trigger fire (#241).
    /// Emitted alongside the underlying `TriggerFired` so audit views
    /// can attribute fires to a user. `event_subtype` distinguishes
    /// surfaces (`"ui_fire"`, `"ui_replay"`, `"cli_fire"`,
    /// `"cli_replay"`); `detail` carries source-specific fields
    /// (manual name, source event id).
    WorkflowManualTriggered {
        workflow_id: String,
        workspace_id: String,
        actor: String,
        event_subtype: String,
        detail: serde_json::Value,
    },

    /// A workflow-tagged artifact entered a new stage.
    StageEntered {
        artifact_id: ArtifactId,
        workflow_id: String,
        stage_index: u32,
        stage_name: String,
    },

    /// A gate on the current stage resolved successfully.
    StageGatePassed {
        artifact_id: ArtifactId,
        workflow_id: String,
        stage_index: u32,
        gate_kind: String,
    },

    /// A gate on the current stage failed. The artifact is parked in
    /// `under_review` until the gate-failure condition is cleared (e.g. a
    /// new CI run succeeds, a reviewer approves).
    StageGateFailed {
        artifact_id: ArtifactId,
        workflow_id: String,
        stage_index: u32,
        gate_kind: String,
        reason: String,
    },

    /// All gates on a stage resolved and the artifact advanced to the next
    /// stage (or reached terminal state when this was the last stage).
    StageAdvanced {
        artifact_id: ArtifactId,
        workflow_id: String,
        from_stage_index: u32,
        /// `None` when the artifact has just completed the final stage.
        to_stage_index: Option<u32>,
    },

    // -- Registry events (factory pipeline foundations, issue #14) ----------
    /// A new artifact type was proposed (not yet active).
    TypeProposed {
        type_id: String,
        workspace_id: String,
        revision: i32,
    },

    /// A proposed type was approved and entered the active catalog.
    TypeApproved {
        type_id: String,
        workspace_id: String,
        revision: i32,
    },

    /// A type was deprecated (retained for audit, not used for new artifacts).
    TypeDeprecated {
        type_id: String,
        workspace_id: String,
        reason: String,
    },

    /// An adapter implementation was registered in the catalog.
    AdapterRegistered {
        adapter_id: String,
        workspace_id: String,
        revision: i32,
    },

    /// An adapter was deprecated.
    AdapterDeprecated {
        adapter_id: String,
        workspace_id: String,
        reason: String,
    },

    /// A gate evaluator was registered.
    GateRegistered {
        evaluator_id: String,
        workspace_id: String,
        revision: i32,
    },

    /// A gate evaluator was deprecated.
    GateDeprecated {
        evaluator_id: String,
        workspace_id: String,
        reason: String,
    },

    /// An agent profile was registered.
    ProfileRegistered {
        profile_id: String,
        workspace_id: String,
        revision: i32,
    },

    /// An agent profile was deprecated.
    ProfileDeprecated {
        profile_id: String,
        workspace_id: String,
        reason: String,
    },

    // -- Workflow events (issue #81 — stiglab workflow CRUD + webhook) ------
    // `TriggerFired` is defined above in the issue #80 block; the stiglab
    // webhook router emits the same variant so forge's trigger subscriber can
    // consume it with no translation.
    /// A GitHub `check_suite`, `check_run`, or `status` event arrived for a
    /// PR we care about. Forge's external-check gate consumes this to advance
    /// or block artifacts whose current stage is `external-check`.
    GateCheckUpdated {
        repo_owner: String,
        repo_name: String,
        pr_number: u64,
        check_name: String,
        conclusion: String,
    },

    /// A manual-approval gate received a signal (e.g. the PR was merged).
    /// Forge's manual-approval gate advances when this arrives.
    GateManualApprovalSignal {
        repo_owner: String,
        repo_name: String,
        pr_number: u64,
        source: String,
    },
}

impl FactoryEventKind {
    /// Returns the dot-separated event type string (e.g., "artifact.registered").
    pub fn event_type(&self) -> &'static str {
        match self {
            Self::ArtifactRegistered { .. } => "artifact.registered",
            Self::ArtifactStateChanged { .. } => "artifact.state_changed",
            Self::ArtifactArchived { .. } => "artifact.archived",
            Self::GitPrOpened { .. } => "git.pr_opened",
            Self::GitCiCompleted { .. } => "git.ci_completed",
            Self::GitPrMerged { .. } => "git.pr_merged",
            Self::GitPrClosed { .. } => "git.pr_closed",
            Self::ForgeShapingDispatched { .. } => "forge.shaping_dispatched",
            Self::ForgeShapingReturned { .. } => "forge.shaping_returned",
            Self::ForgeGateRequested { .. } => "forge.gate_requested",
            Self::ForgeGateVerdict { .. } => "forge.gate_verdict",
            Self::ForgeInsightObserved { .. } => "forge.insight_observed",
            Self::ForgeDecisionMade { .. } => "forge.decision_made",
            Self::StiglabSessionCompleted { .. } => "stiglab.session_completed",
            Self::StiglabShapingResultReady { .. } => "stiglab.shaping_result_ready",
            Self::StiglabSessionFailed { .. } => "stiglab.session_failed",
            Self::StiglabSessionAborted { .. } => "stiglab.session_aborted",
            Self::PortalSessionRequested { .. } => "portal.session_requested",
            Self::SynodicGateEvaluated { .. } => "synodic.gate_evaluated",
            Self::SynodicGateDenied { .. } => "synodic.gate_denied",
            Self::SynodicGateModified { .. } => "synodic.gate_modified",
            Self::SynodicGateVerdict { .. } => "synodic.gate_verdict",
            Self::SynodicEscalationStarted { .. } => "synodic.escalation_started",
            Self::SynodicEscalationResolved { .. } => "synodic.escalation_resolved",
            Self::SynodicEscalationTimedOut { .. } => "synodic.escalation_timed_out",
            Self::SynodicGateResolutionProposed { .. } => "synodic.gate_resolution_proposed",
            Self::SynodicRuleProposed { .. } => "synodic.rule_proposed",
            Self::SynodicRuleApproved { .. } => "synodic.rule_approved",
            Self::SynodicRuleDisabled { .. } => "synodic.rule_disabled",
            Self::SynodicRuleVersionCreated { .. } => "synodic.rule_version_created",
            Self::IsingInsightDetected { .. } => "ising.insight_detected",
            Self::IsingInsightEmitted { .. } => "ising.insight_emitted",
            Self::IsingInsightSuppressed { .. } => "ising.insight_suppressed",
            Self::IsingRuleProposed { .. } => "ising.rule_proposed",
            Self::IsingAnalyzerError { .. } => "ising.analyzer_error",
            Self::IsingCatchupCompleted { .. } => "ising.catchup_completed",
            Self::IntentSubmitted { .. } => "refract.intent_submitted",
            Self::RefractDecomposed { .. } => "refract.decomposed",
            Self::RefractFailed { .. } => "refract.failed",
            Self::TriggerFired { .. } => "trigger.fired",
            Self::WorkflowManualTriggered { .. } => "workflow.manual_triggered",
            Self::StageEntered { .. } => "stage.entered",
            Self::StageGatePassed { .. } => "stage.gate_passed",
            Self::StageGateFailed { .. } => "stage.gate_failed",
            Self::StageAdvanced { .. } => "stage.advanced",
            Self::TypeProposed { .. } => "registry.type_proposed",
            Self::TypeApproved { .. } => "registry.type_approved",
            Self::TypeDeprecated { .. } => "registry.type_deprecated",
            Self::AdapterRegistered { .. } => "registry.adapter_registered",
            Self::AdapterDeprecated { .. } => "registry.adapter_deprecated",
            Self::GateRegistered { .. } => "registry.gate_registered",
            Self::GateDeprecated { .. } => "registry.gate_deprecated",
            Self::ProfileRegistered { .. } => "registry.profile_registered",
            Self::ProfileDeprecated { .. } => "registry.profile_deprecated",
            Self::GateCheckUpdated { .. } => "gate.check_updated",
            Self::GateManualApprovalSignal { .. } => "gate.manual_approval_signal",
        }
    }

    /// Returns the stream_type for this event.
    pub fn stream_type(&self) -> &'static str {
        match self {
            Self::ArtifactRegistered { .. }
            | Self::ArtifactStateChanged { .. }
            | Self::ArtifactArchived { .. } => "artifact",
            Self::GitPrOpened { .. }
            | Self::GitCiCompleted { .. }
            | Self::GitPrMerged { .. }
            | Self::GitPrClosed { .. } => "git",
            Self::ForgeShapingDispatched { .. }
            | Self::ForgeShapingReturned { .. }
            | Self::ForgeGateRequested { .. }
            | Self::ForgeGateVerdict { .. }
            | Self::ForgeInsightObserved { .. }
            | Self::ForgeDecisionMade { .. } => "forge",
            Self::StiglabSessionCompleted { .. }
            | Self::StiglabShapingResultReady { .. }
            | Self::StiglabSessionFailed { .. }
            | Self::StiglabSessionAborted { .. } => "stiglab",
            Self::PortalSessionRequested { .. } => "portal",
            Self::SynodicGateEvaluated { .. }
            | Self::SynodicGateDenied { .. }
            | Self::SynodicGateModified { .. }
            | Self::SynodicGateVerdict { .. }
            | Self::SynodicEscalationStarted { .. }
            | Self::SynodicEscalationResolved { .. }
            | Self::SynodicEscalationTimedOut { .. }
            | Self::SynodicGateResolutionProposed { .. }
            | Self::SynodicRuleProposed { .. }
            | Self::SynodicRuleApproved { .. }
            | Self::SynodicRuleDisabled { .. }
            | Self::SynodicRuleVersionCreated { .. } => "synodic",
            Self::IsingInsightDetected { .. }
            | Self::IsingInsightEmitted { .. }
            | Self::IsingInsightSuppressed { .. }
            | Self::IsingRuleProposed { .. }
            | Self::IsingAnalyzerError { .. }
            | Self::IsingCatchupCompleted { .. } => "ising",
            Self::IntentSubmitted { .. }
            | Self::RefractDecomposed { .. }
            | Self::RefractFailed { .. } => "refract",
            Self::TriggerFired { .. }
            | Self::StageEntered { .. }
            | Self::StageGatePassed { .. }
            | Self::StageGateFailed { .. }
            | Self::StageAdvanced { .. } => "workflow",
            // Audit-only fan-out for manual fires (#241). Lives in the
            // `audit` namespace so audit views can filter without
            // mixing with first-class workflow runtime events.
            Self::WorkflowManualTriggered { .. } => "audit",
            Self::TypeProposed { .. }
            | Self::TypeApproved { .. }
            | Self::TypeDeprecated { .. }
            | Self::AdapterRegistered { .. }
            | Self::AdapterDeprecated { .. }
            | Self::GateRegistered { .. }
            | Self::GateDeprecated { .. }
            | Self::ProfileRegistered { .. }
            | Self::ProfileDeprecated { .. } => "registry",
            Self::GateCheckUpdated { .. } | Self::GateManualApprovalSignal { .. } => "gate",
        }
    }

    /// Returns the primary entity ID this event relates to.
    pub fn stream_id(&self) -> String {
        match self {
            Self::ArtifactRegistered { artifact_id, .. }
            | Self::ArtifactStateChanged { artifact_id, .. }
            | Self::ArtifactArchived { artifact_id, .. } => artifact_id.to_string(),
            Self::GitPrOpened { artifact_id, .. }
            | Self::GitCiCompleted { artifact_id, .. }
            | Self::GitPrMerged { artifact_id, .. }
            | Self::GitPrClosed { artifact_id, .. } => artifact_id.to_string(),
            Self::ForgeShapingDispatched { request_id, .. } => request_id.clone(),
            Self::ForgeShapingReturned { request_id, .. } => request_id.clone(),
            Self::ForgeGateRequested { artifact_id, .. } => artifact_id.to_string(),
            Self::ForgeGateVerdict { artifact_id, .. } => artifact_id.to_string(),
            Self::ForgeInsightObserved { insight_id, .. } => insight_id.clone(),
            Self::ForgeDecisionMade { artifact_id, .. } => artifact_id.to_string(),
            Self::StiglabSessionCompleted { session_id, .. }
            | Self::StiglabSessionFailed { session_id, .. }
            | Self::StiglabSessionAborted { session_id, .. } => session_id.clone(),
            Self::StiglabShapingResultReady { artifact_id, .. } => artifact_id.to_string(),
            Self::PortalSessionRequested { session_id, .. } => session_id.clone(),
            Self::SynodicGateEvaluated { gate_id, .. } => gate_id.clone(),
            Self::SynodicGateDenied { gate_id, .. } => gate_id.clone(),
            Self::SynodicGateModified { gate_id, .. } => gate_id.clone(),
            Self::SynodicGateVerdict { gate_id, .. } => gate_id.clone(),
            Self::SynodicEscalationStarted { escalation_id, .. } => escalation_id.clone(),
            Self::SynodicEscalationResolved { escalation_id, .. } => escalation_id.clone(),
            Self::SynodicEscalationTimedOut { escalation_id, .. } => escalation_id.clone(),
            Self::SynodicGateResolutionProposed { escalation_id, .. } => escalation_id.clone(),
            Self::SynodicRuleProposed { rule_id, .. } => rule_id.clone(),
            Self::SynodicRuleApproved { rule_id, .. } => rule_id.clone(),
            Self::SynodicRuleDisabled { rule_id, .. } => rule_id.clone(),
            Self::SynodicRuleVersionCreated { rule_id, .. } => rule_id.clone(),
            Self::IsingInsightDetected { insight_id, .. } => insight_id.clone(),
            Self::IsingInsightEmitted { subject_ref, .. } => subject_ref.clone(),
            Self::IsingInsightSuppressed { insight_id, .. } => insight_id.clone(),
            Self::IsingRuleProposed { insight_id, .. } => insight_id.clone(),
            Self::IsingAnalyzerError { analyzer, .. } => analyzer.clone(),
            Self::IsingCatchupCompleted { .. } => "ising".to_string(),
            Self::IntentSubmitted { intent_id, .. }
            | Self::RefractDecomposed { intent_id, .. }
            | Self::RefractFailed { intent_id, .. } => intent_id.clone(),
            Self::TriggerFired { workflow_id, .. } => format!("workflow:{workflow_id}"),
            Self::WorkflowManualTriggered { workflow_id, .. } => {
                format!("audit:workflow:{workflow_id}")
            }
            Self::StageEntered { artifact_id, .. }
            | Self::StageGatePassed { artifact_id, .. }
            | Self::StageGateFailed { artifact_id, .. }
            | Self::StageAdvanced { artifact_id, .. } => format!("workflow:{artifact_id}"),
            Self::TypeProposed { type_id, .. }
            | Self::TypeApproved { type_id, .. }
            | Self::TypeDeprecated { type_id, .. } => format!("type:{type_id}"),
            Self::AdapterRegistered { adapter_id, .. }
            | Self::AdapterDeprecated { adapter_id, .. } => format!("adapter:{adapter_id}"),
            Self::GateRegistered { evaluator_id, .. }
            | Self::GateDeprecated { evaluator_id, .. } => format!("gate:{evaluator_id}"),
            Self::ProfileRegistered { profile_id, .. }
            | Self::ProfileDeprecated { profile_id, .. } => format!("profile:{profile_id}"),
            Self::GateCheckUpdated {
                repo_owner,
                repo_name,
                pr_number,
                ..
            }
            | Self::GateManualApprovalSignal {
                repo_owner,
                repo_name,
                pr_number,
                ..
            } => format!("{repo_owner}/{repo_name}#{pr_number}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Supporting enums
// ---------------------------------------------------------------------------

/// Outcome of a shaping request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ShapingOutcome {
    Completed,
    Failed,
    Partial,
    Aborted,
}

/// Gate points where Synodic is consulted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GatePoint {
    PreDispatch,
    StateTransition,
    ConsumerRouting,
    ToolLevel,
}

/// Summary of a Synodic verdict (for event spine recording).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerdictSummary {
    Allow,
    Deny,
    Modify,
    Escalate,
}

/// Forge process states. Used by forge's internal state machine; no longer
/// carried on a `FactoryEventKind` variant after spec #272 retired
/// `ForgeStateChanged`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ForgeProcessState {
    Running,
    Paused,
    Draining,
    Stopped,
}

/// Insight categories from Ising.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InsightKind {
    Failure,
    Waste,
    Win,
    Anomaly,
}

/// Scope of an insight.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InsightScope {
    ArtifactKind(String),
    SpecificArtifact(ArtifactId),
    Global,
}

/// How an escalation was resolved.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EscalationResolution {
    Approved,
    Denied,
    TimedOut,
}

/// Reference to a spine event used as evidence for a signal (`insight.emitted`
/// variant carries a `Vec<EventRef>`). This is the spine-native counterpart to
/// `onsager_spine::protocol::FactoryEventRef` — kept in the spine crate so the event
/// vocabulary has no protocol-crate dependency.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EventRef {
    /// The `id` column in the `events` or `events_ext` table.
    pub event_id: i64,
    /// The `event_type` string (e.g. `"forge.gate_verdict"`), for quick
    /// consumer-side filtering without a second lookup.
    pub event_type: String,
}

/// LLM token usage carried on [`FactoryEventKind::StiglabSessionCompleted`]
/// (issue #39). Accounting primitives only — USD cost is resolved downstream
/// by the budget consumer, not on the event, so we don't have to version the
/// pricing table every time a model changes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct TokenUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    /// Cache-read input tokens (Anthropic-style prompt caching). Zero for
    /// providers without a cache concept.
    #[serde(default)]
    pub cache_read_tokens: u64,
    /// Cache-creation input tokens.
    #[serde(default)]
    pub cache_write_tokens: u64,
    /// Model identifier (`"claude-sonnet-4-6"`, etc.) so the downstream
    /// pricing table can resolve cost without guessing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

/// What kind of rule change an [`FactoryEventKind::IsingRuleProposed`] is
/// asking Synodic to make.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum RuleProposalAction {
    /// Disable or retire an existing rule — typically when override rate is
    /// so high the rule is more friction than value.
    Retire { rule_id: String },
    /// Rewrite an existing rule's condition — typically when the rule is
    /// tripping on false positives.
    Rewrite {
        rule_id: String,
        suggested_condition: Option<String>,
    },
    /// Register a new rule for a subject that currently has none.
    Introduce {
        subject_ref: String,
        suggested_condition: Option<String>,
    },
}

/// How a rule proposal should be handled by Synodic.
///
/// `SafeAuto` proposals carry a narrow, reversible change with enough
/// confidence that blocking on a human is pure friction. `ReviewRequired`
/// proposals land in the review queue on the dashboard.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleProposalClass {
    SafeAuto,
    ReviewRequired,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[path = "factory_event_tests.rs"]
#[cfg(test)]
mod tests;
