//! `cargo run -p xtask -- check-metaphor-leakage`
//!
//! Spec #469 / ADR 0019 — the AI-factory metaphor is retired from the
//! dashboard's substrate-facing surfaces (chrome, in-app copy, chat
//! persona). A small set of surfaces explicitly keeps the metaphor
//! (marketing-adjacent pages, template-content `factory_framing`
//! strings, the `New workflow` command's `factory` keyword alias).
//!
//! This lint scans `apps/dashboard/src/` for the metaphor's vocabulary
//! and fails when it appears outside the explicitly-kept locations.
//! The marketing app (`apps/marketing/`) is not scanned — KB explicitly
//! permits metaphor copy there.
//!
//! The substring set was lifted directly from the spec's Plan ("zero
//! remaining `factory` / `factory floor` / `QC checkpoint` / `AI
//! factory operator` strings outside the explicitly-kept locations"),
//! plus `inspection report` and `factory operator` from the chat-
//! persona slot the spec listed in its Decision body.
//!
//! Escape hatches:
//! - **Path allowlist** (`KEPT_PATHS`): files whose entire contents are
//!   permitted to mention the metaphor. Each entry carries a reason so
//!   a future reader can audit it.
//! - **Inline `// metaphor-allow: <reason>`**: same-line escape for a
//!   single hit (Rust / TS / JS comment shape). Reason text is
//!   mandatory and grep-able.
//! - **JSON `_metaphor_allow` top-level key**: the inline-comment shape
//!   doesn't fit JSON, so files whose top-level object carries a
//!   non-empty `_metaphor_allow` string are exempt. Same shape as
//!   `_comment` in `v0.json`.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};

const SCAN_ROOT: &str = "apps/dashboard/src";

/// Case-insensitive substrings whose presence in substrate-facing copy
/// is a metaphor leak. Order does not matter; matches are reported per
/// line with the offending needle named.
const NEEDLES: &[&str] = &[
    "factory floor",
    "ai factory operator",
    "factory operator",
    "qc checkpoint",
    "qc checkpoints",
    "inspection report",
    "inspection reports",
    // Bare "factory" stays last so the more-specific phrases above
    // report first when they overlap.
    "factory",
];

/// Files whose entire contents are exempt. Per ADR 0019 the metaphor
/// is **kept** on marketing-adjacent surfaces, on template-content
/// `factory_framing` strings, and on the `New workflow` command's
/// `factory` keyword alias. The technical references (auto-generated
/// types, comments referencing the Rust `FactoryEventKind` enum, the
/// TS type definition for the kept JSON field, and the chat assistant's
/// own negative-rule mention) are also kept.
const KEPT_PATHS: &[(&str, &str)] = &[
    (
        "apps/dashboard/src/pages/LandingPage.tsx",
        "marketing landing — metaphor kept per ADR 0019 KB position",
    ),
    (
        "apps/dashboard/src/pages/ShowcaseDogfoodPage.tsx",
        "public showcase — metaphor kept per ADR 0019 KB position",
    ),
    // `apps/dashboard/src/lib/templates/v0.json` is exempted via its
    // top-level `_metaphor_allow` JSON field rather than this path
    // list, so the JSON escape hatch sees real use and the v0 catalog
    // can document its kept-by-design rationale inline.
    (
        "apps/dashboard/src/lib/templates/index.ts",
        "TS type for `factory_framing` field on the kept JSON content",
    ),
    (
        "apps/dashboard/src/components/chat/TemplateGallery.tsx",
        "renders the kept `factory_framing` template content",
    ),
    (
        "apps/dashboard/src/components/layout/CommandPalette.tsx",
        "`factory` retained as a keyword alias on the `New workflow` command (ADR 0019)",
    ),
    (
        "apps/dashboard/src/lib/chat/llm-client.ts",
        "system prompt names metaphor terms as the *anti-pattern* the LLM must avoid",
    ),
    (
        "apps/dashboard/src/lib/api/registry.ts",
        "comment references the Rust `FactoryEventKind` enum (technical)",
    ),
];

/// Path prefixes (directories) whose contents are entirely exempt.
const KEPT_PREFIXES: &[(&str, &str)] = &[(
    "apps/dashboard/src/lib/api/generated/",
    "auto-generated by ts-rs from the Rust `FactoryEventKind` enum",
)];

pub fn run() -> Result<()> {
    let root = workspace_root()?;
    let scan_dir = root.join(SCAN_ROOT);
    let files = collect_files(&scan_dir)?;

    let mut violations: Vec<Violation> = Vec::new();
    let mut allowed_files: usize = 0;
    let mut inline_allowed: Vec<Violation> = Vec::new();

    for file in &files {
        let rel = file.strip_prefix(&root).unwrap_or(file);
        if let Some(reason) = path_allow(rel) {
            allowed_files += 1;
            let _ = reason; // accepted-by-allowlist, no per-file output
            continue;
        }
        let text =
            std::fs::read_to_string(file).with_context(|| format!("read {}", file.display()))?;
        if has_json_allow(file, &text) {
            allowed_files += 1;
            continue;
        }
        for hit in scan_text(&text) {
            let v = Violation {
                path: rel.to_path_buf(),
                line_no: hit.line_no,
                needle: hit.needle,
                snippet: hit.snippet,
            };
            if has_inline_allow(&v.snippet) {
                inline_allowed.push(v);
            } else {
                violations.push(v);
            }
        }
    }

    if !inline_allowed.is_empty() {
        eprintln!("check-metaphor-leakage: inline metaphor-allow exemptions:");
        for v in &inline_allowed {
            eprintln!(
                "  {}:{} [{}] {}",
                v.path.display(),
                v.line_no,
                v.needle,
                v.snippet.trim()
            );
        }
        eprintln!();
    }

    if violations.is_empty() {
        println!(
            "check-metaphor-leakage: clean ({} file(s) scanned, {} kept-by-allowlist, {} inline-allowed)",
            files.len(),
            allowed_files,
            inline_allowed.len()
        );
        return Ok(());
    }

    eprintln!(
        "check-metaphor-leakage: {} metaphor leak(s) outside the kept allowlist:",
        violations.len()
    );
    for v in &violations {
        eprintln!(
            "  {}:{} [{}] {}",
            v.path.display(),
            v.line_no,
            v.needle,
            v.snippet.trim()
        );
    }
    eprintln!();
    eprintln!("ADR 0019 retired the AI-factory metaphor from the dashboard's substrate-facing");
    eprintln!("surfaces (spec #469). Either rewrite in substrate-native vocabulary (Workflow /");
    eprintln!("Run / Artifact / Stage; Drafted / Bound / Active / Paused), add the path to");
    eprintln!("KEPT_PATHS in xtask/src/check_metaphor_leakage.rs with a reason, or add an");
    eprintln!("inline `// metaphor-allow: <reason>` on the offending line.");
    bail!("metaphor-leakage lint failed");
}

#[derive(Debug)]
struct Violation {
    path: PathBuf,
    line_no: usize,
    needle: &'static str,
    snippet: String,
}

#[derive(Debug, PartialEq, Eq)]
struct Hit {
    needle: &'static str,
    line_no: usize,
    snippet: String,
}

fn scan_text(text: &str) -> Vec<Hit> {
    let mut out: Vec<Hit> = Vec::new();
    let mut seen: Vec<(usize, &'static str)> = Vec::new();
    for (idx, line) in text.lines().enumerate() {
        let lower = line.to_lowercase();
        let line_no = idx + 1;
        for needle in NEEDLES {
            if !lower.contains(needle) {
                continue;
            }
            // Prefer the more-specific overlap: if a longer phrase
            // already matched on this line at the same position, skip
            // the bare `factory` follow-up.
            if *needle == "factory"
                && seen
                    .iter()
                    .any(|(ln, n)| *ln == line_no && n.contains("factory"))
            {
                continue;
            }
            seen.push((line_no, needle));
            out.push(Hit {
                needle,
                line_no,
                snippet: line.to_string(),
            });
        }
    }
    out
}

fn has_inline_allow(snippet: &str) -> bool {
    let idx = match snippet.find("metaphor-allow:") {
        Some(i) => i,
        None => return false,
    };
    let reason = snippet[idx + "metaphor-allow:".len()..].trim();
    // Allow the reason to wrap to end-of-line; trim trailing comment
    // closers if present (`*/`).
    let trimmed = reason.trim_end_matches("*/").trim();
    !trimmed.is_empty()
}

/// JSON files can't carry `//` comments. A top-level `_metaphor_allow`
/// string field (any non-empty value) exempts the file. Same shape as
/// the existing `_comment` field in `v0.json`.
fn has_json_allow(path: &Path, text: &str) -> bool {
    if path.extension().and_then(|s| s.to_str()) != Some("json") {
        return false;
    }
    let value: serde_json::Value = match serde_json::from_str(text) {
        Ok(v) => v,
        Err(_) => return false,
    };
    let obj = match value.as_object() {
        Some(o) => o,
        None => return false,
    };
    obj.get("_metaphor_allow")
        .and_then(|v| v.as_str())
        .is_some_and(|s| !s.trim().is_empty())
}

fn path_allow(path: &Path) -> Option<&'static str> {
    let s = path.to_string_lossy();
    for (kept, reason) in KEPT_PATHS {
        if s == *kept {
            return Some(reason);
        }
    }
    for (prefix, reason) in KEPT_PREFIXES {
        if s.starts_with(prefix) {
            return Some(reason);
        }
    }
    None
}

fn workspace_root() -> Result<PathBuf> {
    let manifest = std::env::var("CARGO_MANIFEST_DIR")
        .context("CARGO_MANIFEST_DIR not set; run via `cargo run -p xtask`")?;
    Ok(Path::new(&manifest)
        .parent()
        .ok_or_else(|| anyhow!("xtask manifest has no parent"))?
        .to_path_buf())
}

fn collect_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    walk(dir, &mut out)?;
    out.sort();
    Ok(out)
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir).with_context(|| format!("read_dir {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if path.is_dir() {
            if matches!(
                name,
                "node_modules" | "dist" | "build" | ".next" | ".turbo" | "out"
            ) {
                continue;
            }
            walk(&path, out)?;
        } else if let Some(ext) = path.extension().and_then(|s| s.to_str())
            && matches!(ext, "ts" | "tsx" | "js" | "jsx" | "json" | "md")
        {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bare_factory_is_a_hit() {
        let hits = scan_text("Start the factory now");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].needle, "factory");
    }

    #[test]
    fn factory_floor_reports_specific_needle_not_bare() {
        let hits = scan_text("name your factory floor");
        // Both `factory floor` and `factory` substring-match; the lint
        // only reports the more-specific one so the error message
        // doesn't double up.
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].needle, "factory floor");
    }

    #[test]
    fn qc_checkpoint_phrases() {
        let hits = scan_text("a QC checkpoint that ships PRs");
        assert!(hits.iter().any(|h| h.needle == "qc checkpoint"));
    }

    #[test]
    fn inline_allow_exempts_a_line() {
        let snippet = r#"const x = "factory" // metaphor-allow: legit reason"#;
        assert!(has_inline_allow(snippet));
    }

    #[test]
    fn inline_allow_requires_a_reason() {
        let snippet = r#"const x = "factory" // metaphor-allow: "#;
        assert!(!has_inline_allow(snippet));
    }

    #[test]
    fn json_top_level_metaphor_allow_exempts_file() {
        let path = PathBuf::from("dummy/v0.json");
        let text = r#"{"_metaphor_allow": "user-facing template content", "templates": []}"#;
        assert!(has_json_allow(&path, text));
    }

    #[test]
    fn json_without_allow_field_is_not_exempt() {
        let path = PathBuf::from("dummy/v0.json");
        let text = r#"{"templates": []}"#;
        assert!(!has_json_allow(&path, text));
    }

    #[test]
    fn path_allow_matches_directory_prefixes() {
        let p = PathBuf::from("apps/dashboard/src/lib/api/generated/TokenUsage.ts");
        assert!(path_allow(&p).is_some());
    }

    #[test]
    fn path_allow_matches_exact_files() {
        let p = PathBuf::from("apps/dashboard/src/pages/LandingPage.tsx");
        assert!(path_allow(&p).is_some());
    }

    #[test]
    fn path_allow_misses_unrelated_files() {
        let p = PathBuf::from("apps/dashboard/src/pages/WorkflowsPage.tsx");
        assert!(path_allow(&p).is_none());
    }

    #[test]
    fn case_insensitive_match() {
        let hits = scan_text("FACTORY operator");
        assert!(hits.iter().any(|h| h.needle == "factory operator"));
    }

    #[test]
    fn live_dashboard_passes_lint() {
        // End-to-end: run the lint against the in-tree dashboard. The
        // lint's purpose is to keep this check green; if it fails, the
        // metaphor leaked into a non-allowlisted file and should be
        // rewritten in substrate-native vocabulary.
        super::run().expect("metaphor-leakage lint must pass on main");
    }
}
